# arguments for dataset
dataset: pascal
nclass: 2
crop_size: 64
data_root: data/landslide

# arguments for training
epochs: 80
batch_size: 32
lr: 0.001  # 4GPUs
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
backbone: resnet50
multi_grid: False
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
